### ISSUE TITLE
Output scenario name not used in final output

### ISSUE THREAD

**Issue by calebbraun** [JGCRI/iamrpt#47]
I ran `generate()` with a scenario control file that specifies a different output scenario than the GCAM scenario. The scenario column in the resulting .csv used the original GCAM scenario name.

I was able to fix the problem by deleting line 357 in mcl.R:
```
if(!('scenario' %in% names(tbl)))
```

Is there a case that this check is necessary? If not, I can submit a PR for the fix.

**Comment by xavier-gutierrez** [comment]
Looks like that's there in the case that no new scenario names are indicated in your scenario control file. Also, it seems that your scenarios should be an attribute of the tbl created in line 356. Do your desired scenario names appear in that table?

**Comment by calebbraun** [comment]
The value of `scen` is the scenario name that I want to appear in the output, however the variable `tbl` does not have it. It does have a scenario column, but that contains the original scenario name, not the new one.

Also, if you do not name an output scenario in the scenario control file, this error is thrown before we get to the check in question:
```
Error in validate1(scenctl, "scenario control", scencols, scenrqd) : 
  Missing data prohibited in these scenario control columns: output scenario
```

**Comment by xavier-gutierrez** [comment]
Line 202 takes the new scenario names from the control file and writes them to `rslts`, which is then passed to `merge_scenarios()`. This is how `scen` has the correct value. Now, if `scen` has the right value, how does tbl get written with the old scenario names? As I said, they should be overwritten in line 202 and it sounds like they are. 

What are your settings for template, scenmerge, fileformat, dataformat, and wideformat?

**Comment by calebbraun** [comment]
Yes, `scen` gets the correct value, but the actual values in the raw data table `tbl` still contain the original scenario name. I would expect this, as `tbl` is the result of looking up the scenario from `rawrslts`. And since `tbl` has a "scenario" column (containing the old scenario name), it never gets rewritten with the new scenario name represented by `scen`. 

I'm calling `generate()` with just the first three required parameters, so all the others are defaults.

**Comment by xavier-gutierrez** [comment]
But `rawrslts` is a bit of a misnomer because the scenario names get rewritten on line 202, between `process_scenarios()` and `merge_scenarios()`. 

What's happening is that `rslts` is a list of lists, where each nested list is identified by its scenario name. Nested inside each of those lists is a df for each variable, which correspond to `tbl` in `merge_scenarios()`. Line 202 renames the nested lists but leaves unmodified the scenario column of each variable df, or `tbl`. 

I pushed a branch titled 'scenario_naming' that takes care of the df's inside of each scenario starting just after the original line 202. I wanted to keep the scenario renaming outside of `merge_scenarios()` so it's clear what's happening at each step of the control loop. Try the branch and if it works for your purposes, then we can do a pull request

**Comment by calebbraun** [comment]
That branch solves the problem, thanks!
